CREATE TABLE TEAMS
(
TEAM_ID NUMBER PRIMARY KEY,
TEAM_NAME VARCHAR2(45) NOT NULL
);

CREATE TABLE CLIENTS
(
CLIENT_ID NUMBER PRIMARY KEY,
CLIENT_FIRST_NAME VARCHAR2(45) NOT NULL,
CLIENT_LAST_NAME VARCHAR2(45) NOT NULL,
CLIENT_PRIMARY_PHONE_NUMBER VARCHAR2(45) NOT NULL,
CLIENT_SECONDARY_PHONE_NUMBER VARCHAR2(45),
CLIENT_ADDRESS VARCHAR2(45) NOT NULL,
CLIENT_ADDRESS_STATE VARCHAR2(45) NOT NULL,
CLIENT_ADDRESS_ZIPCODE NUMBER NOT NULL,
CLIENT_BIRTHDAY DATE NOT NULL,
CLIENT_HEIGHT VARCHAR2(45) NOT NULL,
CLIENT_WEIGHT  VARCHAR2(45) NOT NULL,
TEAM_ID NUMBER REFERENCES TEAMS(TEAM_ID),
POSITION VARCHAR2(10) NOT NULL,
YEARS_ACTIVE_IN_SPORT NUMBER NOT NULL 
);

CREATE TABLE EMERGENCY_CONTACT
(
EMERGENCY_CONTACT_ID NUMBER PRIMARY KEY,
CONTACT_FIRST_NAME VARCHAR2(45) NOT NULL,
CONTACT_LAST_NAME VARCHAR2(45) NOT NULL,
CONTACT_PHONE VARCHAR2(45) NOT NULL,
CURRENT_POSITION VARCHAR2(45) NOT NULL,
CLIENT_ID NUMBER REFERENCES CLIENTS(CLIENT_ID)
);

CREATE TABLE MEDICAL_HISTORY
(
CASE_ID NUMBER PRIMARY KEY,
CASE_DATE DATE NOT NULL,
CASE_LOCATION VARCHAR2(45) NOT NULL,
HOSPITAL VARCHAR2(45),
CONDITION VARCHAR2(45) NOT NULL,
PRIMARY_PHYSICAIN VARCHAR2(45) NOT NULL,
PHYSICAIN_CONTACT VARCHAR2(45) NOT NULL,
CLIENT_ID NUMBER REFERENCES CLIENTS(CLIENT_ID)
);


CREATE TABLE G_FORCE_MOUTHGUARD
(
PRODUCT_ID NUMBER PRIMARY KEY,
MANUFACTURER VARCHAR2(45) NOT NULL,
MANUFACTURE_DATE DATE NOT NULL,
IN_STORE VARCHAR2(45) NOT NULL
);

CREATE TABLE G_FORCE_RECORD
(
RECORD_ID NUMBER PRIMARY KEY,
G_FORCE_LEVEL NUMBER NOT NULL,
RECORD_DATE DATE NOT NULL,
G_FORCE_PRODUCT_ID REFERENCES G_FORCE_MOUTHGUARD(PRODUCT_ID),
CLIENT_ID REFERENCES CLIENTS(CLIENT_ID)
);
